spring:
  application:
    name: yourorder-customer

  datasource:
    url: jdbc:postgresql://localhost:5434/yourorder_customer
    username: customer_user
    password: customer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8082